### ISSUE TITLE
Try To Make All In One Page

### ISSUE THREAD

**Issue by aljawaid** [aljawaid/ContentCleaner#10]
I'd suggest something like this:

# Template

[Select all] [Select none]  // convenience buttons

- [ ] Cleaning job A
- [ ] Cleaning job B

[Run cleaner...]  // Go with selected, let but confirm first

Styling this is fully up to you. :wink:

# Controller
```php
public function cleanUp() 
{
   // Invoke dedicated model function for each selected job.
}
```
# Model
```php
public function resetCalendarSettings() 
{
} 
public function jobA()
{
}
public function jobB()
{
}
```
Model contains tons of helper functions like
```php
private function resetSettings($fields = array()) 
{
}
```

_Originally posted by @alfredbuehler in https://github.com/aljawaid/ContentCleaner/issues/4#issuecomment-1466583954_

**Comment by aljawaid** [comment]
@alfredbuehler @creecros i dont think i will do this, simply as i dont know how.... cant get my head around it.

plus @creecros said once that unselecting checkboxes doesnt work in kanboard. so i have always avoided checkboxes.

I think I will stick to individual cleaning jobs

**Comment by creecros** [comment]
@alfredbuehler implemented checkboxs very easily in mailmagik, look at that for guidance.
