### ISSUE TITLE
Create Cleaning Jobs for Plugins

### ISSUE THREAD

**Issue by aljawaid** [aljawaid/ContentCleaner#11]
- [x] Create `JSON` file to store all relevant plugin information
- [x] Create helper
- [x] Create model
- [x] Create controller for modal form
- [x] Add job to template

**Comment by aljawaid** [comment]
### JSON Keys:

- `"2": {` 
  - _Identification number to match the cleaning job number_
-  `"plugin_name": ` 
   - _Plugin name as saved in `plugin_schema_versions` table_
-  `"plugin_author":` 
   - _Plugin author name_
- `"plugin_url": ` 
  - _URL is needed in case of forks/plugins with the same name_
  - _Will be shown in the template_
- `"checked_upto_plugin_version": ` 
  - _For easy reference and future updates_
  - _Will be shown in the template_
- `"plugin_tables": ` 
  - _Database tables which are **added by the plugin**_
  - _Will be shown as a list in the template_
  - _Will be shown as a count in the template_
- `"core_table_columns":` 
  - _Additional columns in **core database** tables_
  - _Will be shown as a list in the template_
  - _Will be shown as a count in the template_
- `"plugin_schema_version": ` 
  - _The schema version set for the plugin in `plugin_schema_versions` table_
  - _Will be used to delete the entry from the table matching the plugin name_

**Comment by aljawaid** [comment]
![image](https://user-images.githubusercontent.com/10233708/234999708-898175e1-6c38-4141-b1fb-f0c07d82a02c.png)

Rough draft of template

**Comment by aljawaid** [comment]
024a4cfa5af55202ad62ed24aaab75e2d07f0fcb

74bc48fc56681d8111579d97a9cfe5db1ef8cc74

**Comment by aljawaid** [comment]
@creecros The frontend for the plugin jobs is done. Any tips of how to do the functioning for deleting the stuff?

I think I can re-use functions like `delete table` or `delete column`... am sure I saw them in the code.

Any tips?

**Comment by aljawaid** [comment]
@creecros The frontend for the plugin jobs is done. Any tips of how to do the functioning for deleting the stuff?

I think I can re-use functions like `delete table` or `delete column`... am sure I saw them in the code.

Any tips?

**Comment by aljawaid** [comment]
Screenshots https://github.com/aljawaid/ContentCleaner/commit/c2d4b1258ce45425cf1d5dad02b4a5f78656e225

**Comment by aljawaid** [comment]
@creecros still busy?

**Comment by creecros** [comment]
Yes and no, I'll try and get back into it
