### ISSUE TITLE
Internal Error: Invalid identifier: TABLE_TYPE

### ISSUE THREAD

**Issue by alfredbuehler** [aljawaid/ContentCleaner#21]
![image](https://github.com/aljawaid/ContentCleaner/assets/2079289/a4618bc4-e6e6-4d31-9ecb-74a7d2bd97f7)

Installed via git clone, as there are no zip files around yet.

**Comment by aljawaid** [comment]
It's strange that. On my 1.2.20 it was fine. But I just updated to the latest version and now I get the same error

**Comment by alfredbuehler** [comment]
If you change it to lowercase, it works.  'TABLE_TYPE' -> 'table_type'
![image](https://github.com/aljawaid/ContentCleaner/assets/2079289/b36f0b9d-d201-4606-923f-8b9945da16ae)
I doubt, this is a clean solution.

**Comment by aljawaid** [comment]
oh great, I will apply the fix shortly.

Is it really MySQL issue though?  Because I only got the issue on my side when I upgraded Kanboard to the latest and ALSO updated php to v8.1 from v7.4.  The database was always the same.

Strange

**Comment by aljawaid** [comment]
> IMHO, for a cleaner solution, you should query the information_schema.COLUMNS as well, to obtain the correct name/case.

@creecros did that part of the code so I don't really understand it myself

**Comment by aljawaid** [comment]
> Where is he? Haven't seen him for a longer while.

no idea, he went quiet since he changed his job

**Comment by creecros** [comment]
I'm alive and well, incognito mode.

**Comment by aljawaid** [comment]
> I'm alive and well, incognito mode.

hehe good to hear... get back on Kanboard and bring the forum back to life.  Good lad :)
