### ISSUE TITLE
Fix settings from a formerly installed calendar plugin

### ISSUE THREAD

**Issue by alfredbuehler** [aljawaid/ContentCleaner#4]
In case no calendar plugin is installed, the two calendar settings

- _calendar_project_tasks_
- _calendar_user_tasks_

should either be removed or reset to the default value _date_started_.

Otherwise, this can follow up to confusing effects. See this [forum thread](https://kanboard.discourse.group/t/ical-data-with-duedate-only/2636).

**Comment by aljawaid** [comment]
https://kanboard.discourse.group/t/ical-data-with-duedate-only/2636/50?u=aljawaid

hello, cool, I will work on including this for the initial release

**Comment by aljawaid** [comment]
@alfredbuehler 
> should either be removed or reset to the default value date_started.

Which do you suggest? If they are removed, will Kanboard recreate them or should they be reset to the default value?

**Comment by alfredbuehler** [comment]
I think, they are present by default. Therefore, it's better to set them to _date_started_.

**Comment by alfredbuehler** [comment]
Yes, for me i'ts OK like this.

**Comment by aljawaid** [comment]
```php
<a href="<?= $this->url->href('CleaningController', 'confirmReset', array('table' => 'settings', 'plugin' => 'ContentCleaner'), false, '', false) ?>" class="btn job-btn js-modal-confirm"><span class="content-cleaner-icon"></span> <?= t('Reset Settings') ?></a>
```

I want to add two more variables for this issue... but for other features, how can I use the same function with unknown number of variables?

This issue needs two fields resetting, so two additional variables can be added to this code and I can follow it through with an `alter table` statement (i hope).... but it got me thinking, what if on the next feature, there are three fields which need resetting?

I was also thinking, maybe just duplicate the function based on number of variables to reset, as and when I come across them.  What do you think?

**Comment by aljawaid** [comment]
or maybe I cant use variables at all, because with two field names, i need to specify the associated value too... im so confused

**Comment by aljawaid** [comment]
what about?
```
<a href="<?= $this->url->href('CleaningController', 'confirmReset', array('table' => 'settings', 'fields' => array('calendar_project_tasks' => 'date_started', 'calendar_user_tasks' => 'date_started' ), 'plugin' => 'ContentCleaner')
```

I have just guessed the above, so maybe it is totally wrong.  I wouldn't know how to call it either but first I need to set them as variables.... otherwise I guess it is a function for each fix/issue/feature

@alfredbuehler @creecros any tips or advice?

**Comment by aljawaid** [comment]
model:

```
public function resetSettings($table, $fields = array())
    {
        // RESET VALUES
        $db->table($table)->eq('option', 'calendar_project_tasks')->update(['value' => 'date_started']);
    }
```

is that right? but then where do I put the $fields and how does it work out foreach of the fields?

**Comment by alfredbuehler** [comment]
It works now, with https://github.com/aljawaid/ContentCleaner/commit/968c4c3fb23e40b0fe1ddee5782dcc9e27de3cd0.

But we should think about the UI again. As soon as more cleaning jobs will be added, we'll end up messy.

**Comment by aljawaid** [comment]
> It works now, with https://github.com/aljawaid/ContentCleaner/commit/968c4c3fb23e40b0fe1ddee5782dcc9e27de3cd0.
> 
> But we should think about the UI again. As soon as more cleaning jobs will be added, we'll end up messy.
> 

Great. Thanks. So does that mean you have done one function for the calendar settings. So basically for future, it will be one new function per job. I'm away from computer so just reading code changes.

About the UI, I have already designed it so that it will be one box per cleaning job. I will keep an eye on it once I have added a few more jobs. This plugin is difficult for me so I'm very slow at it as I'm not good with dB side of stuff. If you have suggestions do let me know.

I previously got up to deleting a table thanks to @creecros but I haven't moved on yet. I need to work on how to combine deleting multiple tables and then also deleting one field from the plugin schemas table. Step by step.

**Comment by alfredbuehler** [comment]
I'd suggest something like this:

# Template

[Select all] [Select none]  // convenience buttons

- [ ] Cleaning job A
- [ ] Cleaning job B

[Run cleaner...]  // Go with selected, let but confirm first

Styling this is fully up to you. :wink:

# Controller
```php
public function cleanUp() 
{
   // Invoke dedicated model function for each selected job.
}
```
# Model
```php
public function resetCalendarSettings() 
{
} 
public function jobA()
{
}
public function jobB()
{
}
```
Model contains tons of helper functions like
```php
private function resetSettings($fields = array()) 
{
}
```

**Comment by aljawaid** [comment]
> I'd suggest something like this:
> # Template
> 
> [Select all] [Select none] // convenience buttons
> 
>     * [ ]  Cleaning job A
> 
>     * [ ]  Cleaning job B
> 
> 
> [Run cleaner...] // Go with selected, let but confirm first
> 
> Styling this is fully up to you. 😉
> # Controller
> 
> ```
> public function cleanUp() 
> {
>    // Invoke dedicated model function for each selected job.
> }
> ```
> 
> # Model
> 
> ```
> public function resetCalendarSettings() 
> {
> } 
> public function jobA()
> {
> }
> public function jobB()
> {
> }
> ```
> 
> Model contains tons of helper functions like
> 
> ```
> private function resetSettings($fields = array()) 
> {
> }
> ```

this would be hard to describe/layout the problem vs solution..... let this plugin develop a bit with a few more cleaning jobs and then we can look at the UI again.  its hard to imagine with just 1 job.

**Comment by alfredbuehler** [comment]
I disagree, but it's your project. I'm here to help if I can.

**Comment by aljawaid** [comment]
> I disagree, but it's your project. I'm here to help if I can.

let's see how it develops... at the moment there is only the calendar fix cleaning job.  the other functions in the models are not fully finished.... just sql statements I have collected which would be useful.

the delete table function works but i havent got round to getting it properly in the frontend yet.

**Comment by alfredbuehler** [comment]
Yes. Each cleaning job has its enable/disable checkbox, created preferably by inserting a sub-template.
The Clean button is shared for all enabled jobs.
Each job has its own model function to perform the effective work.

IMHO this will lead to an easy to extend design, when adding new jobs: 
- Write a template for the job.
- Insert it in the main template.
- Write the appropriate model function.

As I wrote earlier, the model functions are getting help from some helper functions, like resetSettings, deleteTable etc.

**Comment by aljawaid** [comment]
@alfredbuehler what about this?

![image](https://user-images.githubusercontent.com/10233708/227068248-b34431f5-c8c7-43de-a495-17d998700910.png)

I would put a button in the highlighted section to complete the above (through a checkbox modal)... and each job is also hidden inside the individual section.

I am 50-50 on this, so I need you to push me one way or another.  OR should i just do YOUR suggested form inside the hidden accordion section.... or should i do it as a modal...

**Comment by alfredbuehler** [comment]
The button is fine, I can live with it. It's up to you to decide, it's your project.
