### ISSUE TITLE
Internal Error: SQL Error[HY000]: SQLSTATE[HY000]: General error: 1 no such table: information_schema.tables

### ISSUE THREAD

**Issue by creecros** [aljawaid/ContentCleaner#5]
Is this a table I am supposed to have?
`Internal Error: SQL Error[HY000]: SQLSTATE[HY000]: General error: 1 no such table: information_schema.tables`

**Comment by aljawaid** [comment]
for mysql yes, for anything i am learning as i go along

**Comment by aljawaid** [comment]
completed in https://github.com/aljawaid/ContentCleaner/commit/14753bef9375a0a396059785f9413076aea04416

**Comment by creecros** [comment]
I can only confirm sqlite support, but I have no idea if postgres and mssql works. fyi.

**Comment by aljawaid** [comment]
ok I will keep it open to review later

**Comment by aljawaid** [comment]
#8
