### ISSUE TITLE
Config page is a bit off on my screen

### ISSUE THREAD

**Issue by creecros** [aljawaid/ContentCleaner#6]
Im just using a 17" laptop @ 1600x900 (16:9)
![image](https://user-images.githubusercontent.com/26339368/224771434-092020b2-9e2a-4504-b846-ed99292084e4.png)

**Comment by aljawaid** [comment]
I will work on this.... laptops piss me off.... even my own shows something different sometimes, even when I account for it.

**Comment by aljawaid** [comment]
what browser you using?

**Comment by aljawaid** [comment]
does f14d642 help?  On firefox with your resolution i cant reproduce it but the changes have made the box a bit neater so maybe it helps on your side

**Comment by creecros** [comment]
> what browser you using?

chrome

**Comment by aljawaid** [comment]
> > what browser you using?
> 
> chrome

![image](https://user-images.githubusercontent.com/10233708/224858956-4850879c-ea94-4f8d-bdb8-842e3e3a89bb.png)


I cant reproduce, maybe my fix fixed it

**Comment by creecros** [comment]
I'll check it tomorrow
