### ISSUE TITLE
MySQL Errors

### ISSUE THREAD

**Issue by aljawaid** [aljawaid/ContentCleaner#8]
List of errors since all the @creecros updates this week, most likely to be MySQL related.

- [ ] `PHP Warning:  Invalid argument supplied for foreach() in /var/www/.../ContentCleaner/Helper/DefaultTableHelper.php on line 187`
- [ ] `PHP Warning:  in_array() expects parameter 2 to be array, object given in /var/www/.../ContentCleaner/Helper/DefaultTableHelper.php on line 61`
- [ ] `PHP Warning:  array_diff(): Expected parameter 1 to be an array, object given in /var/www/.../public_html/plugins/ContentCleaner/Helper/DefaultTableHelper.php on line 210`
- [ ]

**Comment by aljawaid** [comment]
https://github.com/aljawaid/ContentCleaner/commit/68227920f0a5074a30c1f5a4098785597e6de2c4 could be wrong, let me list the other errors I am getting

**Comment by creecros** [comment]
yes I know that's wrong. look at sqlite one that works. it finds only 1 column, name.  the mysql has to have the same return, an array with only that 1 column of names, or it won't work.

**Comment by creecros** [comment]
actually reading your errors, it seems your return is an object. so, it's possible that it is correct, im not sure, but you need to convert the object to an array. try typecasting it.

put `(array)` in front of it.

http://ocramius.github.io/blog/fast-php-object-to-array-conversion/

**Comment by creecros** [comment]
i still need to look deep into this, i feel like something is not right. I switched to Mysql, so at least i can test it now.

**Comment by creecros** [comment]
ok, it should be good to go now for Mysql. 

I tested all them buttons and no issues, so far. I added 'schema_version' to the default table list manually. It is not in the Default Schema file for mysql, but it is definately a table you need as it the equivelant of 'plugin_schema_versions' for the main application schema. This table does not exist in sqlite. 

Now, postgres, and mssql. I have no clue. I can put up a postgres server to test, but not sure about mssql.

**Comment by aljawaid** [comment]
thanks for all the above, I am yet to pull the changes...

What I dont understand is... if we are using `if``driver` statements then why not just use the relevant statement using `$this->db->execute` because in the docs it says it is okay.... 

on the other hand, in phpMyAdmin, `SHOW COLUMNS FROM 'mytable'`works

also,yeh I dont use a test version, im working on my live kanboard as i go along which is why im slower and will ot be using the delete functions.... I did a test table function for that reason so i can make sure it works.

I will get into discord, later tonight

**Comment by creecros** [comment]
its alright, mysql works fine now. fully tested.

postgres, works as well, although i did not fully test delete function when there were uninstalled plugins as of yet. but 100% ok to push the button when there are plugins installed.

I have been using db->execute at this point when i get stumped. just requires me to figure out what i get in return. example:
https://github.com/aljawaid/ContentCleaner/blob/3902ed81515dc693a6a54aca2f060a7d78040b2b/Model/ApplicationCleaningModel.php#L112-L119

notice the double loop just to get the info that i needed out of it. 

all i know, is each db is different, by a large factor. this is a learning curve.

working on mssql in a bit, spinning up a server for it now.

**Comment by creecros** [comment]
although, I just noticed I hard coded the db name in there...

**Comment by creecros** [comment]
ya i cant find a good mssql docker image....ima say, dont support that for now.

**Comment by aljawaid** [comment]
![image](https://user-images.githubusercontent.com/10233708/226490706-1285492e-f256-499f-bdc8-c914df4128ca.png)

@creecros I thought we were both getting 47 default tables? whats your mysql showing now after all your code changes?

**Comment by aljawaid** [comment]
> ya i cant find a good mssql docker image....ima say, dont support that for now.

done f2979070ac6509607862ff8953341220bf1b5d4e

**Comment by creecros** [comment]
> ![image](https://user-images.githubusercontent.com/10233708/226490706-1285492e-f256-499f-bdc8-c914df4128ca.png)
> 
> @creecros I thought we were both getting 47 default tables? whats your mysql showing now after all your code changes?

reread:
https://github.com/aljawaid/ContentCleaner/issues/8#issuecomment-1474877283
